### PR TITLE
Exclude Stateless Samples

### PR DESCRIPTION
**Pull request by mathowar**

### CODE REVIEW

**Comment by JapNolt** [comment]
@mathowar Curious why these samples are being removed? Is support for stateless SDK changing?

**Comment by mathowar** [comment]
> @mathowar Curious why these samples are being removed? Is support for stateless SDK changing?

@JapNolt, these samples were accidentally pushed before they were completed. Once completed they will be readded

**Comment by JapNolt** [comment]
> @mathowar Curious why these samples are being removed? Is support for stateless SDK changing?
> 
> @JapNolt, these samples were accidentally pushed before they were completed. Once completed they will be readded

Awesome!! Any thoughts on timeline of release of these samples?

**Comment by mathowar** [comment]
> > @mathowar Curious why these samples are being removed? Is support for stateless SDK changing?
> > @JapNolt, these samples were accidentally pushed before they were completed. Once completed they will be readded
> 
> Awesome!! Any thoughts on timeline of release of these samples?

@JapNolt, I will let you know as soon as I know, however I am not the owner of those samples. I'll contact the owner and see what they say, but as of now there is no timeline.

**Pull request closed without merging**
